name: agrisync
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  firebase_core: ^3.12.0
  firebase_auth: ^5.3.4
  google_sign_in: ^6.2.2
  intl: ^0.20.1
  cloud_firestore: ^5.6.0
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  shared_preferences: ^2.3.5
  curved_navigation_bar: ^1.0.6
  http: ^1.3.0
  amazon_cognito_identity_dart_2: ^3.8.0
  percent_indicator: ^4.2.4
  fl_chart: ^0.70.2
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  firebase_database: ^11.3.3
  url_launcher: ^6.3.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/paw.png
    - assets/shoppingCart.png
    - assets/plant.png
    - assets/photo.png